import { Book, User, ReadingList, Post, Author, Highlight, AuthorNote, Comment, ReadingProgress } from '../types';

// Mock Books Data - Using actual cover images from assets
export const MOCK_BOOKS: Book[] = [
  {
    id: 'dune',
    title: 'Dune',
    author: 'Frank Herbert',
    authorId: 'author-1',
    coverUrl: require('../assets/images/homepage/Dune.png'),
    description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.',
    isbn: '9780441172719',
    publishedDate: '1965-08-01',
    genres: ['Science Fiction', 'Fantasy', 'Adventure'],
    rating: 4.4,
    totalRatings: 18392,
    pageCount: 688,
    language: 'English',
    publisher: 'Ace Books',
    tags: ['classic', 'epic', 'space-opera'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'city-of-orange',
    title: 'City of Orange',
    author: 'David Yoon',
    authorId: 'author-2',
    coverUrl: require('../assets/images/homepage/City_of_Orange.png'),
    description: 'A man wakes up in a hospital with no memory of how he got there. As he tries to piece together his identity, he discovers a world that seems both familiar and strange.',
    isbn: '9780735211292',
    publishedDate: '2021-03-16',
    genres: ['Fiction', 'Mystery', 'Contemporary'],
    rating: 4.1,
    totalRatings: 8643,
    pageCount: 320,
    language: 'English',
    publisher: 'G.P. Putnam\'s Sons',
    tags: ['mystery', 'identity', 'contemporary'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'the-moon',
    title: 'The Moon and Stars',
    author: 'Jenna Warren',
    authorId: 'author-3',
    coverUrl: require('../assets/images/homepage/The_Moon.png'),
    description: 'A beautiful tale of love, loss, and finding hope in the darkest of times. Follow Luna as she navigates through life\'s challenges guided by the celestial bodies above.',
    isbn: '9781501161933',
    publishedDate: '2022-06-13',
    genres: ['Fiction', 'Romance', 'Literary Fiction'],
    rating: 4.3,
    totalRatings: 12254,
    pageCount: 280,
    language: 'English',
    publisher: 'Atria Books',
    tags: ['romance', 'literary', 'emotional'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'dont-look-back',
    title: "Don't Look Back",
    author: 'Isaac Nelson',
    authorId: 'author-4',
    coverUrl: require('../assets/images/homepage/Dont_look_back.png'),
    description: 'A gripping thriller about a woman who must confront her past when her carefully constructed new life begins to unravel.',
    isbn: '9780735219090',
    publishedDate: '2023-08-14',
    genres: ['Thriller', 'Mystery', 'Suspense'],
    rating: 4.5,
    totalRatings: 15847,
    pageCount: 384,
    language: 'English',
    publisher: 'Random House',
    tags: ['thriller', 'suspense', 'page-turner'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'tarzan',
    title: 'Tarzan',
    author: 'Edgar Rice Burroughs',
    authorId: 'author-5',
    coverUrl: require('../assets/images/homepage/Tarzan.png'),
    description: 'The classic adventure tale of a man raised by apes in the African jungle, discovering his true identity and place in both the wild and civilized worlds.',
    isbn: '9780486284958',
    publishedDate: '1912-10-01',
    genres: ['Adventure', 'Classic', 'Fiction'],
    rating: 4.0,
    totalRatings: 25847,
    pageCount: 312,
    language: 'English',
    publisher: 'A.C. McClurg & Co.',
    tags: ['classic', 'adventure', 'jungle'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'walk-into-shadow',
    title: 'Walk Into the Shadow',
    author: 'John Waters',
    authorId: 'author-6',
    coverUrl: require('../assets/images/homepage/Salman.png'),
    description: 'A haunting psychological thriller that explores the depths of human nature and the shadows that lurk within us all.',
    isbn: '9780544716278',
    publishedDate: '2023-03-21',
    genres: ['Psychological Thriller', 'Horror', 'Fiction'],
    rating: 4.2,
    totalRatings: 9847,
    pageCount: 368,
    language: 'English',
    publisher: 'Houghton Mifflin',
    tags: ['psychological', 'dark', 'thriller'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'harry-potter',
    title: 'Harry Potter and the Philosopher\'s Stone',
    author: 'J.K. Rowling',
    authorId: 'author-7',
    coverUrl: require('../assets/images/homepage/Harry_potter.png'),
    description: 'The magical story of a young wizard who discovers his true heritage and begins his journey at Hogwarts School of Witchcraft and Wizardry.',
    isbn: '9780747532699',
    publishedDate: '1997-06-26',
    genres: ['Fantasy', 'Young Adult', 'Adventure'],
    rating: 4.7,
    totalRatings: 125847,
    pageCount: 223,
    language: 'English',
    publisher: 'Bloomsbury',
    tags: ['magic', 'wizard', 'bestseller', 'classic'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'sisters',
    title: 'Sisters',
    author: 'Raina Telgemeier',
    authorId: 'author-8',
    coverUrl: require('../assets/images/homepage/Sisters.png'),
    description: 'A heartwarming graphic memoir about family, growing up, and the complicated relationship between sisters.',
    isbn: '9780545540599',
    publishedDate: '2014-08-26',
    genres: ['Graphic Novel', 'Memoir', 'Young Adult'],
    rating: 4.4,
    totalRatings: 18247,
    pageCount: 200,
    language: 'English',
    publisher: 'Graphix',
    tags: ['graphic-novel', 'family', 'memoir'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'the-summer',
    title: 'The Summer I Turned Pretty',
    author: 'Jenny Han',
    authorId: 'author-9',
    coverUrl: require('../assets/images/homepage/The_Summer.png'),
    description: 'A coming-of-age story about first love, family secrets, and the bittersweet nature of growing up during one unforgettable summer.',
    isbn: '9781416968290',
    publishedDate: '2009-05-05',
    genres: ['Young Adult', 'Romance', 'Contemporary'],
    rating: 4.1,
    totalRatings: 22847,
    pageCount: 276,
    language: 'English',
    publisher: 'Simon & Schuster',
    tags: ['summer', 'romance', 'coming-of-age'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// Mock Users Data
export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    email: 'alex.reader@example.com',
    displayName: 'Alex Johnson',
    username: 'alexreads',
    profilePicture: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    isAuthor: false,
    bio: 'Passionate reader of sci-fi and fantasy novels. Always looking for the next great adventure.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    preferences: {
      favoriteGenres: ['Science Fiction', 'Fantasy', 'Mystery'],
      readingGoal: 50,
      notificationsEnabled: true,
      privacySettings: {
        profileVisibility: 'public',
        readingListsVisibility: 'public',
        activityVisibility: 'friends',
      },
    },
    stats: {
      totalBooksRead: 127,
      currentlyReading: 3,
      totalReadingLists: 8,
      followersCount: 245,
      followingCount: 189,
    },
  },
  {
    id: 'user-2',
    email: 'sarah.bookworm@example.com',
    displayName: 'Sarah Chen',
    username: 'sarahbookworm',
    profilePicture: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    isAuthor: true,
    bio: 'Romance author and avid reader. Love stories that make you believe in love again.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    preferences: {
      favoriteGenres: ['Romance', 'Contemporary Fiction', 'Young Adult'],
      readingGoal: 75,
      notificationsEnabled: true,
      privacySettings: {
        profileVisibility: 'public',
        readingListsVisibility: 'public',
        activityVisibility: 'public',
      },
    },
    stats: {
      totalBooksRead: 234,
      currentlyReading: 2,
      totalReadingLists: 12,
      followersCount: 1247,
      followingCount: 456,
    },
  },
];

// Mock Reading Lists Data
export const MOCK_READING_LISTS: ReadingList[] = [
  {
    id: 'list-1',
    userId: 'user-1',
    name: 'Sci-Fi Favorites',
    description: 'My all-time favorite science fiction novels',
    books: [MOCK_BOOKS[2], MOCK_BOOKS[0]], // Dune, Midnight Library
    isPublic: true,
    coverImages: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop',
    ],
    totalBooks: 2,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['sci-fi', 'favorites', 'classics'],
  },
  {
    id: 'list-2',
    userId: 'user-1',
    name: 'Currently Reading',
    description: 'Books I\'m reading right now',
    books: [MOCK_BOOKS[1], MOCK_BOOKS[3]], // Atomic Habits, Seven Husbands
    isPublic: false,
    coverImages: [
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    ],
    totalBooks: 2,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['current', 'in-progress'],
  },
  {
    id: 'list-3',
    userId: 'user-2',
    name: 'Romance Must-Reads',
    description: 'The best romance novels everyone should read',
    books: [MOCK_BOOKS[3], MOCK_BOOKS[4]], // Seven Husbands, Crawdads
    isPublic: true,
    coverImages: [
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    ],
    totalBooks: 2,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['romance', 'must-read', 'recommendations'],
  },
];

// Mock Posts Data
export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    userId: 'user-1',
    user: MOCK_USERS[0],
    content: 'Just finished reading Dune for the third time and I\'m still discovering new layers to this masterpiece! The world-building is absolutely incredible.',
    bookId: '3',
    book: MOCK_BOOKS[2],
    type: 'book-review',
    likes: 23,
    commentsCount: 8,
    isLiked: false,
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
    tags: ['review', 'sci-fi', 'classic'],
  },
  {
    id: 'post-2',
    userId: 'user-2',
    user: MOCK_USERS[1],
    content: 'Currently reading "The Seven Husbands of Evelyn Hugo" and I can\'t put it down! The storytelling is phenomenal. Has anyone else read this?',
    bookId: '4',
    book: MOCK_BOOKS[3],
    type: 'recommendation',
    likes: 45,
    commentsCount: 12,
    isLiked: true,
    createdAt: '2024-01-14T14:20:00Z',
    updatedAt: '2024-01-14T14:20:00Z',
    tags: ['currently-reading', 'recommendation'],
  },
  {
    id: 'post-3',
    userId: 'user-1',
    user: MOCK_USERS[0],
    content: '"The only way to make sense out of change is to plunge into it, move with it, and join the dance." - Alan Watts',
    type: 'quote',
    likes: 67,
    commentsCount: 15,
    isLiked: true,
    createdAt: '2024-01-13T09:15:00Z',
    updatedAt: '2024-01-13T09:15:00Z',
    tags: ['quote', 'inspiration', 'philosophy'],
  },
];

// Mock Authors Data
export const MOCK_AUTHORS: Author[] = [
  {
    ...MOCK_USERS[1],
    books: [MOCK_BOOKS[3]], // Sarah wrote Seven Husbands (in our mock world)
    notes: [],
    publishedBooksCount: 3,
    totalReaders: 15000,
    bio: 'Sarah Chen is a bestselling romance author known for her emotionally rich stories and complex characters. She has published three novels and is working on her fourth.',
    website: 'https://sarahchen.com',
    socialLinks: {
      twitter: '@sarahchenwrites',
      instagram: '@sarahchenwrites',
      facebook: 'SarahChenAuthor',
    },
  },
  {
    id: 'author-2',
    email: 'elena.martinez@example.com',
    displayName: 'Elena Martinez',
    username: 'elenamartinez',
    profilePicture: 'https://randomuser.me/api/portraits/women/44.jpg',
    isAuthor: true,
    bio: 'Award-winning author of historical fiction and literary thrillers.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    preferences: {
      favoriteGenres: ['Historical Fiction', 'Thriller'],
      readingGoal: 40,
      notificationsEnabled: true,
      privacySettings: {
        profileVisibility: 'public',
        readingListsVisibility: 'public',
        activityVisibility: 'public',
      },
    },
    stats: {
      totalBooksRead: 98,
      currentlyReading: 1,
      totalReadingLists: 5,
      followersCount: 3200,
      followingCount: 210,
    },
    books: [
      {
        ...MOCK_BOOKS[0],
        title: 'The Lost Letters',
        id: 'book-100',
      },
    ],
    notes: [],
    publishedBooksCount: 2,
    totalReaders: 8000,
    website: 'https://elenamartinez.com',
    socialLinks: {
      twitter: '@elena_martinez',
      instagram: '@elena.martinez.author',
    },
  },
  {
    id: 'author-3',
    email: 'david.nguyen@example.com',
    displayName: 'David Nguyen',
    username: 'davidnguyen',
    profilePicture: 'https://randomuser.me/api/portraits/men/32.jpg',
    isAuthor: true,
    bio: 'Science fiction and fantasy writer. Dreamer of new worlds.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    preferences: {
      favoriteGenres: ['Science Fiction', 'Fantasy'],
      readingGoal: 60,
      notificationsEnabled: true,
      privacySettings: {
        profileVisibility: 'public',
        readingListsVisibility: 'public',
        activityVisibility: 'public',
      },
    },
    stats: {
      totalBooksRead: 150,
      currentlyReading: 2,
      totalReadingLists: 7,
      followersCount: 5400,
      followingCount: 340,
    },
    books: [
      {
        ...MOCK_BOOKS[2],
        title: 'Stars Beyond Reach',
        id: 'book-101',
      },
    ],
    notes: [],
    publishedBooksCount: 4,
    totalReaders: 12000,
    website: 'https://davidnguyenwrites.com',
    socialLinks: {
      twitter: '@davidnguyen',
      instagram: '@davidnguyenwrites',
    },
  },
];

// Genre constants
export const GENRES = [
  'Fiction',
  'Romance',
  'Mystery',
  'Science Fiction',
  'Fantasy',
  'Thriller',
  'Biography',
  'History',
  'Self-Help',
  'Psychology',
  'Philosophy',
  'Young Adult',
  'Contemporary Fiction',
  'Literary Fiction',
  'Historical Fiction',
  'Horror',
  'Adventure',
  'Crime',
  'Drama',
  'Poetry',
];

// Mock Comments Data
export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'comment-1',
    postId: 'post-1',
    userId: 'user-2',
    user: MOCK_USERS[1],
    content: 'I completely agree! The political intrigue in Dune is what makes it timeless.',
    likes: 5,
    isLiked: false,
    createdAt: '2024-01-15T11:00:00Z',
    updatedAt: '2024-01-15T11:00:00Z',
  },
  {
    id: 'comment-2',
    postId: 'post-1',
    userId: 'user-1',
    user: MOCK_USERS[0],
    content: 'Thanks for the recommendation! Just added it to my reading list.',
    likes: 2,
    isLiked: true,
    createdAt: '2024-01-15T11:30:00Z',
    updatedAt: '2024-01-15T11:30:00Z',
  },
  {
    id: 'comment-3',
    postId: 'post-2',
    userId: 'user-1',
    user: MOCK_USERS[0],
    content: 'This book is on my TBR! Your review just moved it to the top of my list.',
    likes: 8,
    isLiked: false,
    createdAt: '2024-01-14T15:00:00Z',
    updatedAt: '2024-01-14T15:00:00Z',
  },
];

// Mock Highlights Data
export const MOCK_HIGHLIGHTS: Highlight[] = [
  {
    id: 'highlight-1',
    userId: 'user-1',
    bookId: '1',
    text: 'Between life and death there is a library, and within that library, the shelves go on forever.',
    color: 'yellow',
    page: 1,
    position: {
      start: 150,
      end: 245,
    },
    note: 'Such a beautiful opening line that sets the entire tone of the book.',
    isPublic: true,
    createdAt: '2024-01-10T14:20:00Z',
    updatedAt: '2024-01-10T14:20:00Z',
  },
  {
    id: 'highlight-2',
    userId: 'user-1',
    bookId: '2',
    text: 'You do not rise to the level of your goals. You fall to the level of your systems.',
    color: 'blue',
    page: 23,
    position: {
      start: 1200,
      end: 1285,
    },
    note: 'This completely changed how I think about goal setting.',
    isPublic: true,
    createdAt: '2024-01-12T09:15:00Z',
    updatedAt: '2024-01-12T09:15:00Z',
  },
  {
    id: 'highlight-3',
    userId: 'user-2',
    bookId: '3',
    text: 'He who controls the spice controls the universe.',
    color: 'green',
    page: 45,
    position: {
      start: 2100,
      end: 2147,
    },
    isPublic: false,
    createdAt: '2024-01-13T16:30:00Z',
    updatedAt: '2024-01-13T16:30:00Z',
  },
];

// Mock Author Notes Data
export const MOCK_AUTHOR_NOTES: AuthorNote[] = [
  {
    id: 'note-1',
    authorId: 'user-2',
    bookId: '4',
    title: 'Character Development Insights',
    content: 'While writing this book, I drew inspiration from real Hollywood stories of the golden age. The complexity of Evelyn\'s character came from wanting to show how public personas can differ from private truths.',
    isPublic: true,
    tags: ['character-development', 'inspiration', 'writing-process'],
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-08T10:00:00Z',
  },
  {
    id: 'note-2',
    authorId: 'author-2',
    bookId: 'book-100',
    title: 'Research Process',
    content: 'For "The Lost Letters", I spent months researching WWII correspondence. The emotional weight of these real letters heavily influenced the narrative structure.',
    isPublic: true,
    tags: ['research', 'historical-fiction', 'wwii'],
    createdAt: '2024-01-05T14:30:00Z',
    updatedAt: '2024-01-05T14:30:00Z',
  },
  {
    id: 'note-3',
    authorId: 'author-3',
    bookId: 'book-101',
    title: 'World-Building Notes',
    content: 'The star system in "Stars Beyond Reach" is based on actual astronomical data. I wanted the science to feel grounded even in this fantastical setting.',
    isPublic: false,
    tags: ['world-building', 'science', 'research'],
    createdAt: '2024-01-07T11:45:00Z',
    updatedAt: '2024-01-07T11:45:00Z',
  },
];

// Mock Reading Progress Data
export const MOCK_READING_PROGRESS: ReadingProgress[] = [
  {
    id: 'progress-1',
    userId: 'user-1',
    bookId: '1',
    currentPage: 120,
    totalPages: 288,
    percentage: 42,
    status: 'reading',
    startedAt: '2024-01-10T08:00:00Z',
    lastReadAt: '2024-01-15T20:30:00Z',
    notes: 'Really enjoying this philosophical approach to life choices.',
  },
  {
    id: 'progress-2',
    userId: 'user-1',
    bookId: '2',
    currentPage: 320,
    totalPages: 320,
    percentage: 100,
    status: 'completed',
    startedAt: '2023-12-01T08:00:00Z',
    completedAt: '2023-12-15T22:00:00Z',
    lastReadAt: '2023-12-15T22:00:00Z',
    notes: 'Excellent practical advice. Implemented several habit changes.',
  },
  {
    id: 'progress-3',
    userId: 'user-2',
    bookId: '3',
    currentPage: 200,
    totalPages: 688,
    percentage: 29,
    status: 'on-hold',
    startedAt: '2024-01-01T10:00:00Z',
    lastReadAt: '2024-01-10T15:30:00Z',
    notes: 'Complex but fascinating. Taking a break to read something lighter.',
  },
  {
    id: 'progress-4',
    userId: 'user-1',
    bookId: '4',
    currentPage: 0,
    totalPages: 400,
    percentage: 0,
    status: 'not-started',
    lastReadAt: '2024-01-15T00:00:00Z',
  },
];

// Default Reading Lists Data
export const DEFAULT_READING_LISTS = {
  WANT_TO_READ: 'Want to Read',
  CURRENTLY_READING: 'Currently Reading',
  READ: 'Read',
};

// Trending and Recommended Books (subsets of MOCK_BOOKS)
export const TRENDING_BOOKS = [MOCK_BOOKS[3], MOCK_BOOKS[4], MOCK_BOOKS[0]]; // Don't Look Back, Tarzan, Dune
export const RECOMMENDED_BOOKS = [MOCK_BOOKS[6], MOCK_BOOKS[7], MOCK_BOOKS[8]]; // Harry Potter, Sisters, The Summer 