import { Book, User, ReadingList, Post, Author } from '../types';

// Mock Books Data
export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    authorId: 'author-1',
    coverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop',
    description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',
    isbn: '9781786892737',
    publishedDate: '2020-08-13',
    genres: ['Fiction', 'Philosophy', 'Contemporary'],
    rating: 4.2,
    totalRatings: 12847,
    pageCount: 288,
    language: 'English',
    publisher: 'Canongate Books',
    tags: ['bestseller', 'award-winner', 'philosophical'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'Atomic Habits',
    author: 'James Clear',
    authorId: 'author-2',
    coverUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    description: 'An easy & proven way to build good habits & break bad ones. Learn how tiny changes in your daily routine can transform your life.',
    isbn: '9780735211292',
    publishedDate: '2018-10-16',
    genres: ['Self-Help', 'Psychology', 'Productivity'],
    rating: 4.6,
    totalRatings: 25643,
    pageCount: 320,
    language: 'English',
    publisher: 'Avery',
    tags: ['bestseller', 'life-changing', 'practical'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'Dune',
    author: 'Frank Herbert',
    authorId: 'author-3',
    coverUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
    description: 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.',
    isbn: '9780441172719',
    publishedDate: '1965-08-01',
    genres: ['Science Fiction', 'Fantasy', 'Adventure'],
    rating: 4.4,
    totalRatings: 18392,
    pageCount: 688,
    language: 'English',
    publisher: 'Ace Books',
    tags: ['classic', 'epic', 'space-opera'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    authorId: 'author-4',
    coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    description: 'Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life.',
    isbn: '9781501161933',
    publishedDate: '2017-06-13',
    genres: ['Fiction', 'Romance', 'Historical Fiction'],
    rating: 4.5,
    totalRatings: 31254,
    pageCount: 400,
    language: 'English',
    publisher: 'Atria Books',
    tags: ['bestseller', 'lgbtq', 'hollywood'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    title: 'Where the Crawdads Sing',
    author: 'Delia Owens',
    authorId: 'author-5',
    coverUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    description: 'For years, rumors of the "Marsh Girl" have haunted Barkley Cove, a quiet town on the North Carolina coast.',
    isbn: '9780735219090',
    publishedDate: '2018-08-14',
    genres: ['Fiction', 'Mystery', 'Literary Fiction'],
    rating: 4.3,
    totalRatings: 22847,
    pageCount: 384,
    language: 'English',
    publisher: 'G.P. Putnam\'s Sons',
    tags: ['bestseller', 'mystery', 'nature'],
    isAvailable: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// Mock Users Data
export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    email: 'alex.reader@example.com',
    displayName: 'Alex Johnson',
    username: 'alexreads',
    profilePicture: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    isAuthor: false,
    bio: 'Passionate reader of sci-fi and fantasy novels. Always looking for the next great adventure.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    preferences: {
      favoriteGenres: ['Science Fiction', 'Fantasy', 'Mystery'],
      readingGoal: 50,
      notificationsEnabled: true,
      privacySettings: {
        profileVisibility: 'public',
        readingListsVisibility: 'public',
        activityVisibility: 'friends',
      },
    },
    stats: {
      totalBooksRead: 127,
      currentlyReading: 3,
      totalReadingLists: 8,
      followersCount: 245,
      followingCount: 189,
    },
  },
  {
    id: 'user-2',
    email: 'sarah.bookworm@example.com',
    displayName: 'Sarah Chen',
    username: 'sarahbookworm',
    profilePicture: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    isAuthor: true,
    bio: 'Romance author and avid reader. Love stories that make you believe in love again.',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    preferences: {
      favoriteGenres: ['Romance', 'Contemporary Fiction', 'Young Adult'],
      readingGoal: 75,
      notificationsEnabled: true,
      privacySettings: {
        profileVisibility: 'public',
        readingListsVisibility: 'public',
        activityVisibility: 'public',
      },
    },
    stats: {
      totalBooksRead: 234,
      currentlyReading: 2,
      totalReadingLists: 12,
      followersCount: 1247,
      followingCount: 456,
    },
  },
];

// Mock Reading Lists Data
export const MOCK_READING_LISTS: ReadingList[] = [
  {
    id: 'list-1',
    userId: 'user-1',
    name: 'Sci-Fi Favorites',
    description: 'My all-time favorite science fiction novels',
    books: [MOCK_BOOKS[2], MOCK_BOOKS[0]], // Dune, Midnight Library
    isPublic: true,
    coverImages: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop',
    ],
    totalBooks: 2,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['sci-fi', 'favorites', 'classics'],
  },
  {
    id: 'list-2',
    userId: 'user-1',
    name: 'Currently Reading',
    description: 'Books I\'m reading right now',
    books: [MOCK_BOOKS[1], MOCK_BOOKS[3]], // Atomic Habits, Seven Husbands
    isPublic: false,
    coverImages: [
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    ],
    totalBooks: 2,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['current', 'in-progress'],
  },
  {
    id: 'list-3',
    userId: 'user-2',
    name: 'Romance Must-Reads',
    description: 'The best romance novels everyone should read',
    books: [MOCK_BOOKS[3], MOCK_BOOKS[4]], // Seven Husbands, Crawdads
    isPublic: true,
    coverImages: [
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    ],
    totalBooks: 2,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
    tags: ['romance', 'must-read', 'recommendations'],
  },
];

// Mock Posts Data
export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    userId: 'user-1',
    user: MOCK_USERS[0],
    content: 'Just finished reading Dune for the third time and I\'m still discovering new layers to this masterpiece! The world-building is absolutely incredible.',
    bookId: '3',
    book: MOCK_BOOKS[2],
    type: 'book-review',
    likes: 23,
    commentsCount: 8,
    isLiked: false,
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-15T10:30:00Z',
    tags: ['review', 'sci-fi', 'classic'],
  },
  {
    id: 'post-2',
    userId: 'user-2',
    user: MOCK_USERS[1],
    content: 'Currently reading "The Seven Husbands of Evelyn Hugo" and I can\'t put it down! The storytelling is phenomenal. Has anyone else read this?',
    bookId: '4',
    book: MOCK_BOOKS[3],
    type: 'recommendation',
    likes: 45,
    commentsCount: 12,
    isLiked: true,
    createdAt: '2024-01-14T14:20:00Z',
    updatedAt: '2024-01-14T14:20:00Z',
    tags: ['currently-reading', 'recommendation'],
  },
  {
    id: 'post-3',
    userId: 'user-1',
    user: MOCK_USERS[0],
    content: '"The only way to make sense out of change is to plunge into it, move with it, and join the dance." - Alan Watts',
    type: 'quote',
    likes: 67,
    commentsCount: 15,
    isLiked: true,
    createdAt: '2024-01-13T09:15:00Z',
    updatedAt: '2024-01-13T09:15:00Z',
    tags: ['quote', 'inspiration', 'philosophy'],
  },
];

// Mock Authors Data
export const MOCK_AUTHORS: Author[] = [
  {
    ...MOCK_USERS[1],
    books: [MOCK_BOOKS[3]], // Sarah wrote Seven Husbands (in our mock world)
    notes: [],
    publishedBooksCount: 3,
    totalReaders: 15000,
    bio: 'Sarah Chen is a bestselling romance author known for her emotionally rich stories and complex characters. She has published three novels and is working on her fourth.',
    website: 'https://sarahchen.com',
    socialLinks: {
      twitter: '@sarahchenwrites',
      instagram: '@sarahchenwrites',
      facebook: 'SarahChenAuthor',
    },
  },
];

// Genre constants
export const GENRES = [
  'Fiction',
  'Romance',
  'Mystery',
  'Science Fiction',
  'Fantasy',
  'Thriller',
  'Biography',
  'History',
  'Self-Help',
  'Psychology',
  'Philosophy',
  'Young Adult',
  'Contemporary Fiction',
  'Literary Fiction',
  'Historical Fiction',
  'Horror',
  'Adventure',
  'Crime',
  'Drama',
  'Poetry',
];

// Trending and Recommended Books (subsets of MOCK_BOOKS)
export const TRENDING_BOOKS = [MOCK_BOOKS[3], MOCK_BOOKS[1], MOCK_BOOKS[0]]; // Seven Husbands, Atomic Habits, Midnight Library
export const RECOMMENDED_BOOKS = [MOCK_BOOKS[2], MOCK_BOOKS[4], MOCK_BOOKS[1]]; // Dune, Crawdads, Atomic Habits 